# Generated by Django 5.1.1 on 2024-10-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='font_color',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='customization',
            name='font_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customization',
            name='font_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customization',
            name='asset_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image')], max_length=5),
        ),
    ]
